server:
  port: 8085

spring:
  profiles:
    include: secret
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:${db.port}:XE
    username: ${db.username}
    password: ${db.password}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  sql:
    init:
      mode: always
      continue-on-error: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kcc.springmini.domain
