server:
  port: 8085

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:${db.port}:xe
    username: ${db.username}
    password: ${db.password}
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: always
      continue-on-error: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kcc.springmini.domain
